export const genreArray = [
  "Action",
  "Action Comedy",
  "Action Thriller",
  "Adventure",
  "Adventure Comedy",
  "Adventure Fantasy",
  "Animation",
  "Anime",
  "Stop-Motion",
  "Biography",
  "Biographical Drama",
  "Comedy",
  "Black Comedy",
  "Romantic Comedy",
  "Satire",
  "Slapstick",
  "Crime",
  "Crime Drama",
  "Crime Thriller",
  "Gangster",
  "Documentary",
  "Docudrama",
  "Mockumentary",
  "Drama",
  "Legal Drama",
  "Medical Drama",
  "Melodrama",
  "Family",
  "Childrens",
  "Fantasy",
  "Dark Fantasy",
  "Epic Fantasy",
  "Urban Fantasy",
  "Film-Noir",
  "Neo-Noir",
  "History",
  "Historical Drama",
  "Horror",
  "Psychological Horror",
  "Slasher",
  "Supernatural Horror",
  "Body Horror",
  "Music",
  "Concert Film",
  "Musical",
  "Jukebox Musical",
  "Mystery",
  "Detective",
  "Whodunit",
  "Romance",
  "Romantic Drama",
  "Romantic Fantasy",
  "Sci-Fi",
  "Cyberpunk",
  "Space Opera",
  "Time Travel",
  "Dystopian",
  "Short",
  "Short Film",
  "Sport",
  "Sports Drama",
  "Superhero",
  "Comic Book Adaptation",
  "Thriller",
  "Psychological Thriller",
  "Political Thriller",
  "Techno-Thriller",
  "War",
  "Anti-War",
  "Western",
  "Spaghetti Western",
  "Revisionist Western",
];
