import type { Metadata } from "next";
import { Poppins, Libre_Baskerville, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/header/nav-bar";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/header/theme-provider";
import Footer from "@/components/footer";
import { CookieBanner } from "@/components/cookie-banner";
import { getConsentStatus } from "@/lib/consent";

const fontSans = Poppins({
  subsets: ["latin"],
  weight: "500",
  variable: "--font-sans",
});
 
const fontSerif = Libre_Baskerville({
  subsets: ["latin"],
  variable: "--font-serif",
});
 
const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const consent = await getConsentStatus();

  return (
    <html
      lang="en"
      className={`h-full ${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="sticky top-0 z-50">
            <NavBar />
          </header>

          <main className="flex-1">{children}</main>
          <Toaster />
          <Footer />

          {/* Show the GDPR cookie banner until the visitor has made a choice */}
          {consent === null && <CookieBanner />}
        </ThemeProvider>
      </body>
    </html>
  );
}

