import type { Metadata } from "next";
import { Poppins, Libre_Baskerville, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components/header/nav-bar";
import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/components/header/theme-provider";
import Footer from "@/components/footer";

const fontSans = Poppins({
  subsets: ["latin"],
  weight: "500",
  variable: "--font-sans",
});
 
const fontSerif = Libre_Baskerville({
  subsets: ["latin"],
  variable: "--font-serif",
});
 
const fontMono = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
});
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontSans.variable} ${fontSerif.variable} ${fontMono.variable} antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-screen sm:h-full flex flex-col">
        <ThemeProvider attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            >

        <header className="sticky top-0 z-50">
          <NavBar />
        </header>

        <main className="flex-1">{children}</main>
        <Toaster />
        <Footer/>
        </ThemeProvider>
      </body>
      
    </html>
  );
}

